services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: co-finance-backend
    env_file:
      - .env
    environment:
      - ALLOWED_ORIGINS=http://localhost:30,http://20.189.76.7:30
    ports:
      - "8080:8080"
    restart: always
  
    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile.prod
      container_name: co-finance-frontend
      ports:
        - "30:80"
      depends_on:
        - backend
      restart: always
